name: testing_exp_1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.27.0
  firebase_auth: ^4.17.7
  google_sign_in: ^6.2.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  animations: ^2.0.7
  month_picker_dialog: 6.0.2
  path: ^1.9.0
  sqflite: ^2.3.0+1
  path_provider: ^2.1.1




  # Your existing dependencies
  syncfusion_flutter_charts: ^29.1.35
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Uncomment and list your assets here if you add any
  # assets:
  #   - images/
